# Generated by Django 3.1.5 on 2021-01-17 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=4096)),
                ('rating', models.BooleanField(default=False)),
                ('date_published', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
