# Generated by Django 3.1.5 on 2021-01-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210117_1919'),
        ('review', '0002_auto_20210117_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='seller',
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.item'),
        ),
    ]
