# Generated by Django 3.1.5 on 2021-01-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210118_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='item',
            new_name='bought_item',
        ),
    ]
