# Generated by Django 3.1.5 on 2021-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210118_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_published',
            field=models.DateField(auto_now=True),
        ),
    ]
