# Generated by Django 3.1.5 on 2021-01-17 19:19

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(max_length=256)),
                ('description_item', models.CharField(max_length=65536)),
                ('price', models.IntegerField()),
                ('date_added', models.DateField(auto_now=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('ended', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=item.models.get_picture_path, verbose_name='Picture')),
            ],
        ),
    ]
