# Generated by Django 3.1.5 on 2021-01-20 18:32

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210118_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=item.models.get_picture_path, verbose_name='Picture'),
        ),
    ]
