# Generated by Django 3.1.5 on 2021-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210120_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
