# Generated by Django 3.1.5 on 2021-01-21 16:55

from django.db import migrations, models
import djn_bb.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20210120_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=djn_bb.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Picture'),
        ),
    ]
